[platformio]
default_envs = esp32dev
data_dir = data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BLUEDROID_ENABLED=1
    -DCONFIG_BT_CLASSIC_ENABLED=1
    -Wall
